runs-on: self-hosted

variables:
  PROJECT_NAME: "PathTracing"
before_script:
  - echo "starting build for %PROJECT_NAME%"
stages:
  - build
build:
  stage: build
  script:
  - echo "Release build..."
  - 'msbuild /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%.sln"'
  artifacts:
    untracked: true
